# This file generates the GitHub Actions matrix.
---
include:
  - board: seeeduino_xiao_ble
    shield: lintilla_left_central rgbled_adapter
    snippet: studio-rpc-usb-uart
    artifact-name: lintilla-left
  - board: seeeduino_xiao_ble
    shield: lintilla_right_peripheral rgbled_adapter
    artifact-name: lintilla-right
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset